version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./db/view_total_transactions_per_day.sql:/docker-entrypoint-initdb.d/view_total_transactions_per_day.sql
  python-runner:
    build:
      context: .
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["sh", "-c", "python scripts/extract_data.py && python scripts/transform_data.py && python scripts/load_data.py"]